"""
Square Skyscraper — Modular Map Piece
Generated by make-model-123d
Units: mm (game units)
"""

from build123d import *

# --- Parameters ---
base_size = 30        # footprint width/depth (grid tile size)
base_height = 3       # base plate thickness
floor_height = 12     # height per floor
num_floors = 5        # number of floors
building_size = 24    # building footprint (inset from base)

window_width = 4      # width of each window cutout
window_height = 6     # height of each window cutout
window_depth = 1.5    # how deep windows are recessed
windows_per_side = 3  # windows per floor per side
window_inset = 1      # vertical offset from floor bottom

# --- Parts ---

def make_base():
    with BuildPart() as base:
        Box(base_size, base_size, base_height)
    return base.part

def make_tower():
    tower_height = num_floors * floor_height
    with BuildPart() as tower:
        Box(building_size, building_size, tower_height)

        # Cut windows on all 4 sides, every floor
        spacing = building_size / (windows_per_side + 1)
        half = building_size / 2

        for floor_idx in range(num_floors):
            z_base = -tower_height / 2 + floor_idx * floor_height + window_inset + window_height / 2

            for win_idx in range(windows_per_side):
                x_pos = -half + spacing * (win_idx + 1)

                # Front face (Y+)
                with Locations((x_pos, half - window_depth / 2, z_base)):
                    Box(window_width, window_depth + 0.5, window_height, mode=Mode.SUBTRACT)

                # Back face (Y-)
                with Locations((x_pos, -half + window_depth / 2, z_base)):
                    Box(window_width, window_depth + 0.5, window_height, mode=Mode.SUBTRACT)

                # Right face (X+)
                with Locations((half - window_depth / 2, x_pos, z_base)):
                    Box(window_depth + 0.5, window_width, window_height, mode=Mode.SUBTRACT)

                # Left face (X-)
                with Locations((-half + window_depth / 2, x_pos, z_base)):
                    Box(window_depth + 0.5, window_width, window_height, mode=Mode.SUBTRACT)

    return tower.part

# --- Assembly ---
base = make_base()
tower = make_tower()

tower_height = num_floors * floor_height
tower_placed = tower.moved(Location((0, 0, base_height / 2 + tower_height / 2)))

result = base + tower_placed

# --- Export ---
export_step(result, "./output/skyscraper_123d.step")
export_stl(result, "./output/skyscraper_123d.stl")

print(f"Exported skyscraper_123d.step and skyscraper_123d.stl")
print(f"  Base: {base_size}x{base_size}x{base_height}mm")
print(f"  Tower: {building_size}x{building_size}x{tower_height}mm ({num_floors} floors)")
print(f"  Total height: {base_height + tower_height}mm")
