"""
Street Straight Tile — Two-Way Road (North-South)
Generated by make-model-123d
Units: mm

A 100x100mm modular square tile with a straight two-way street running
north-to-south. Road is recessed 0.5mm below the base surface with a
center line divider. Sidewalks on both sides are raised 1mm above the
base surface. Edges are flush for seamless tiling.
"""

from build123d import *

# --- Parameters ---
tile_width = 100        # X dimension (east-west)
tile_depth = 100        # Y dimension (north-south)
base_height = 5         # Total base plate thickness

road_width = 30         # Width of road surface
road_recess = 0.5       # How far road sits below base top surface
center_line_width = 2   # Width of center divider line
center_line_height = 0.3  # Height of center line above road surface
dash_length = 10        # Length of each center line dash
dash_gap = 8            # Gap between dashes

sidewalk_width = 10     # Width of raised sidewalk on each side
sidewalk_raise = 1      # How much sidewalk is raised above base top

curb_width = 2          # Width of curb transition between road and sidewalk
curb_height = 1.5       # Height of curb above road (= recess + raise)

# Derived
road_surface_z = base_height - road_recess   # Z of road surface top
sidewalk_z = base_height + sidewalk_raise     # Z of sidewalk top

# --- Parts ---

# Base plate — full 100x100x5 slab
with BuildPart() as part:
    # Start with the full base plate
    Box(tile_width, tile_depth, base_height,
        align=(Align.CENTER, Align.CENTER, Align.MIN))

    # Cut the road channel — runs full length in Y (north-south)
    with BuildSketch(Plane.XY.offset(base_height - road_recess)):
        Rectangle(road_width, tile_depth)
    extrude(amount=road_recess, mode=Mode.SUBTRACT)

    # Add raised sidewalks — one on each side of the road
    # East sidewalk
    east_sidewalk_x = (road_width / 2) + curb_width + (sidewalk_width / 2)
    with BuildSketch(Plane.XY.offset(base_height)):
        with Locations((east_sidewalk_x, 0)):
            Rectangle(sidewalk_width, tile_depth)
    extrude(amount=sidewalk_raise)

    # West sidewalk
    west_sidewalk_x = -east_sidewalk_x
    with BuildSketch(Plane.XY.offset(base_height)):
        with Locations((west_sidewalk_x, 0)):
            Rectangle(sidewalk_width, tile_depth)
    extrude(amount=sidewalk_raise)

    # Add curbs — small raised strips between road and sidewalks
    # East curb
    east_curb_x = (road_width / 2) + (curb_width / 2)
    with BuildSketch(Plane.XY.offset(road_surface_z)):
        with Locations((east_curb_x, 0)):
            Rectangle(curb_width, tile_depth)
    extrude(amount=curb_height)

    # West curb
    west_curb_x = -east_curb_x
    with BuildSketch(Plane.XY.offset(road_surface_z)):
        with Locations((west_curb_x, 0)):
            Rectangle(curb_width, tile_depth)
    extrude(amount=curb_height)

    # Center line dashes — dashed yellow line pattern
    dash_y_start = -tile_depth / 2 + dash_gap / 2
    num_dashes = int(tile_depth / (dash_length + dash_gap))
    for i in range(num_dashes + 1):
        y_pos = dash_y_start + i * (dash_length + dash_gap)
        if y_pos + dash_length / 2 <= tile_depth / 2:
            with BuildSketch(Plane.XY.offset(road_surface_z)):
                with Locations((0, y_pos)):
                    Rectangle(center_line_width, dash_length)
            extrude(amount=center_line_height)

result = part.part

# --- Export ---
export_step(result, "./output/street_straight_123d.step")
export_stl(result, "./output/street_straight_123d.stl")

print("Exported: street_straight_123d.step, street_straight_123d.stl")
